name: monitoring
services:
  sonarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.0
    container_name: sonarr-exporter
    command: ["sonarr"]
    environment:
      PORT: 9707
      URL: "http://${DOCKER_HOST}:8989"
      APIKEY: ${SONARR_API_KEY}
      ENABLE_ADDITIONAL_METRICS: true
    ports:
      - "9707:9707"
    restart: unless-stopped
  radarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.0
    container_name: radarr-exporter
    command: ["radarr"]
    environment:
      PORT: 9708
      URL: "http://${DOCKER_HOST}:7878"
      APIKEY: ${RADARR_API_KEY}
    ports:
      - "9708:9708"
    restart: unless-stopped
  lidarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.0
    container_name: lidarr-exporter
    command: ["lidarr"]
    environment:
      PORT: 9709
      URL: "http://${DOCKER_HOST}:8686"
      APIKEY: ${LIDARR_API_KEY}
    ports:
      - "9709:9709"
    restart: unless-stopped
  prowlarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.0
    container_name: prowlarr-exporter
    command: ["prowlarr"]
    environment:
      PORT: 9710
      URL: "http://${DOCKER_HOST}:9696"
      APIKEY: ${PROWLARR_API_KEY}
    ports:
     - "9710:9710"
    restart: unless-stopped
  readarr-exporter:
    image: ghcr.io/onedr0p/exportarr:v2.0
    container_name: readarr-exporter
    command: ["readarr"]
    environment:
      PORT: 9711
      URL: "http://${DOCKER_HOST}:8787"
      APIKEY: ${READARR_API_KEY}
    ports:
      - "9711:9711"
    restart: unless-stopped
  deluge-exporter:
    image: ngosang/deluge-exporter:latest
    container_name: deluge-exporter
    environment:
      TZ: Etc/UTC
      DELUGE_URL: http://${DOCKER_HOST}:8112
      DELUGE_PASSWORD: ${DELUGE_PASS}
      LOG_LEVEL: INFO
    ports:
      - "8011:8011"
    restart: unless-stopped
  pihole-exporter:
    image: ekofr/pihole-exporter:latest
    container_name: pihole-exporter
    environment:
      PIHOLE_PROTOCOL: https
      PIHOLE_HOSTNAME: ${PIHOLE_HOSTNAME}
      PIHOLE_PASSWORD: ${PIHOLE_PASS}
      PIHOLE_PORT: 443
      PORT: 9617
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs:ro
    ports:
      - "9617:9617"
    restart: unless-stopped
